#!/bin/bash

# cilova branch, ktera se releasuje, typicky release
DST_BRANCH="release"
if [ ! -z "$1" ]; then
    DST_BRANCH="$1"
fi

# zjisteni nazvu aktualni branche - typicky master
cb=`git rev-parse --abbrev-ref HEAD`
# co do cilove branche && ziskani zmen && merge puvodni branche && predani zmen && navrat do puvodni branche
git push && git checkout $DST_BRANCH && git pull && git merge --ff $cb && git push && git co $cb